name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H rahuldave.us >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          docker run --name f1a7b96621a7ac3f914242a71aaf41e2ce668b_d0a1c7 --label f1a7b9 --workdir /github/workspace --rm \
          -e "INPUT_BRANCH=main" \
          -e "INPUT_GIT_REMOTE_URL=ssh://docker@rahuldave.us:22/official_genaiserver_wl" \
          -e "INPUT_SSH_PRIVATE_KEY=$(cat ~/.ssh/id_rsa)" \
          -e "INPUT_CI_BRANCH_NAME" \
          -e "INPUT_CI_COMMIT" \
          -e "INPUT_COMMAND=deploy" \
          -e "INPUT_DEPLOY_DOCKER_IMAGE" \
          -e "INPUT_DEPLOY_USER_NAME" \
          -e "INPUT_DEPLOY_USER_EMAIL" \
          -e "INPUT_GIT_PUSH_FLAGS" \
          -e "INPUT_REVIEW_APP_NAME" \
          -e "INPUT_SSH_HOST_KEY" \
          -e "INPUT_TRACE" \
          -e "BRANCH" \
          -e "CI_BRANCH_NAME" \
          -e "CI_COMMIT" \
          -e "COMMAND" \
          -e "DEPLOY_DOCKER_IMAGE" \
          -e "DEPLOY_USER_NAME" \
          -e "DEPLOY_USER_EMAIL" \
          -e "GIT_PUSH_FLAGS" \
          -e "GIT_REMOTE_URL" \
          -e "REVIEW_APP_NAME" \
          -e "SSH_HOST_KEY" \
          -e "SSH_PRIVATE_KEY" \
          -e "TRACE" \
          -e "HOME" \
          -e "GITHUB_JOB" \
          -e "GITHUB_REF" \
          -e "GITHUB_SHA" \
          -e "GITHUB_REPOSITORY" \
          -e "GITHUB_REPOSITORY_OWNER" \
          -e "GITHUB_REPOSITORY_OWNER_ID" \
          -e "GITHUB_RUN_ID" \
          -e "GITHUB_RUN_NUMBER" \
          -e "GITHUB_RETENTION_DAYS" \
          -e "GITHUB_RUN_ATTEMPT" \
          -e "GITHUB_REPOSITORY_ID" \
          -e "GITHUB_ACTOR_ID" \
          -e "GITHUB_ACTOR" \
          -e "GITHUB_TRIGGERING_ACTOR" \
          -e "GITHUB_WORKFLOW" \
          -e "GITHUB_HEAD_REF" \
          -e "GITHUB_BASE_REF" \
          -e "GITHUB_EVENT_NAME" \
          -e "GITHUB_SERVER_URL" \
          -e "GITHUB_API_URL" \
          -e "GITHUB_GRAPHQL_URL" \
          -e "GITHUB_REF_NAME" \
          -e "GITHUB_REF_PROTECTED" \
          -e "GITHUB_REF_TYPE" \
          -e "GITHUB_WORKFLOW_REF" \
          -e "GITHUB_WORKFLOW_SHA" \
          -e "GITHUB_WORKSPACE" \
          -e "GITHUB_ACTION" \
          -e "GITHUB_EVENT_PATH" \
          -e "GITHUB_ACTION_REPOSITORY" \
          -e "GITHUB_ACTION_REF" \
          -e "GITHUB_PATH" \
          -e "GITHUB_ENV" \
          -e "GITHUB_STEP_SUMMARY" \
          -e "GITHUB_STATE" \
          -e "GITHUB_OUTPUT" \
          -e "RUNNER_OS" \
          -e "RUNNER_ARCH" \
          -e "RUNNER_NAME" \
          -e "RUNNER_ENVIRONMENT" \
          -e "RUNNER_TOOL_CACHE" \
          -e "RUNNER_TEMP" \
          -e "RUNNER_WORKSPACE" \
          -e "ACTIONS_RUNTIME_URL" \
          -e "ACTIONS_RUNTIME_TOKEN" \
          -e "ACTIONS_CACHE_URL" \
          -e "ACTIONS_RESULTS_URL" \
          -e GITHUB_ACTIONS=true \
          -e CI=true \
          --entrypoint "/bin/dokku-deploy" \
          -v "/var/run/docker.sock":"/var/run/docker.sock" \
          -v "/home/runner/work/_temp/_github_home":"/github/home" \
          -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
          -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" \
          -v "/home/runner/work/official_genaiserver_wl/official_genaiserver_wl":"/github/workspace" \
          f1a7b9:6621a7ac3f914242a71aaf41e2ce668b
