name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_PRIVATE_KEY }}" > ~/.ssh/notwoojinlee713_rsa
          chmod 600 ~/.ssh/notwoojinlee713_rsa
          ssh-keyscan -H rahuldave.us >> ~/.ssh/known_hosts

      - name: Test SSH connection
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/notwoojinlee713_rsa -o StrictHostKeyChecking=no"
        run: ssh -v -T docker@rahuldave.us -p 22 || true # Adding verbosity for debugging

      - name: Push to Dokku
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/notwoojinlee713_rsa -o StrictHostKeyChecking=no"
        run: |
          git remote add dokku ssh://docker@rahuldave.us:22/official_genaiserver_wl
          git push dokku main:master
