name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DOKKU_PRIVATE_KEY }}

      - name: Push to dokku
        run: |
          git remote add dokku ssh://dokku@rahuldave.us:22/officialgenaiserverwl
          git push dokku main:master
